/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package accenture.poc;

import java.io.IOException;

import com.fasterxml.jackson.databind.ObjectMapper;

import accenture.poc.controller.CLIController;
import accenture.poc.services.CountryService;

public class App {

    public static void main(String[] args) {
        CLIController cliController = new CLIController();
        try {
            cliController.controller();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
