/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package accenture.poc;

import java.io.IOException;

import accenture.poc.controller.CLIController;

public class App {

    public static void main(String[] args) {
        CLIController cliController = new CLIController();
        try {
            cliController.controller();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
