/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package accenture.poc;

import com.fasterxml.jackson.databind.ObjectMapper;

import accenture.poc.services.CountryService;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        CountryService countryService = new CountryService();
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            System.out.println(objectMapper.writeValueAsString(countryService.getAllCountries()));
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
